name: Buil

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Build
      run: |
        ./gradlew assembleDebug
    - name: Store generated APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-float
        path: |
          ./app/build/outputs/apk/debug/termux-float-debug.apk
          ./app/build/outputs/apk/debug/output-metadata.json
